### ISSUE TITLE
TypeError: Cannot read property ... of undefined

### ISSUE THREAD

**Issue by CSchulz** [kopach/karma-sabarivka-reporter#226]
If there is an error during the test execution the reporter fails:

```
HeadlessChrome 83.0.4103 (Linux 0.0.0) ERROR
  An error was thrown in afterAll
  Uncaught [object Object] thrown
HeadlessChrome 83.0.4103 (Linux 0.0.0): Executed 212 of 672 ERROR (2.777 secs / 2.406 secs)
10 09 2020 07:25:37.681:ERROR [karma-server]: TypeError: Cannot read property 'projects/commons/src/public_api-dev.ts' of undefined
    at node_modules/karma-sabarivka-reporter/src/instrumenter.ts:35:18
    at Array.forEach (<anonymous>)
    at addFileListToCoverageData (node_modules/karma-sabarivka-reporter/src/instrumenter.ts:32:16)
    at exports.sabarivkaReporter.Object.defineProperty.value.onBrowserComplete (node_modules/karma-sabarivka-reporter/src/instrumenter.ts:16:5)
    at Server.<anonymous> (node_modules/karma/lib/events.js:40:26)
    at Server.emit (events.js:208:15)
    at Browser.onComplete (node_modules/karma/lib/browser.js:95:20)
    at Socket.<anonymous> (node_modules/karma/lib/browser.js:212:44)
    at Socket.emit (events.js:208:15)
    at node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by kopach** [comment]
Hi @CSchulz. What version of karma/TypeScript you use? Could you, please, also double check if you get any similar error from any other karma plugin if this one is disabled?

**Comment by CSchulz** [comment]
Typescript 3.5.3
Karma 4.1.0

Yes it also occurs if I disable all other stuff.

**Comment by kopach** [comment]
hi @CSchulz. I've just released fix for this in version `3.2.4`. Please, check it out if it works for you now.

**Comment by kopach** [comment]
@CSchulz, closing this ticket as of now. Please, reopen it if issue is still reproducible for you. Also consider starring this project if you like it. Thanks

**Comment by CSchulz** [comment]
No further crashes for the moment. 😃
