### ISSUE TITLE
Issue with override keyword

### ISSUE THREAD

**Issue by sebastianteres** [kopach/karma-sabarivka-reporter#486]
### The following issue can be reproduced with [this repository](https://github.com/sebastianteres/issues-sabarivka-ts-override)

I started using TS `override` keyword, turned on tsconfig `noImplicitOverride` flag and tests started failing with the following error:

```sh
> issues-sabarivka-ts-override@0.0.0 test /Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override
> ng test "--code-coverage"

⠙ Generating browser application bundles (phase: building)...27 11 2021 12:49:26.640:WARN [karma]: No captured browser, open http://localhost:9877/
27 11 2021 12:49:26.661:INFO [karma-server]: Karma v6.3.9 server started at http://localhost:9877/
27 11 2021 12:49:26.661:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
27 11 2021 12:49:26.666:INFO [launcher]: Starting browser Chrome
✔ Browser application bundle generation complete.
27 11 2021 12:49:31.470:WARN [karma]: No captured browser, open http://localhost:9877/
27 11 2021 12:49:31.549:INFO [Chrome 96.0.4664.55 (Mac OS 10.15.7)]: Connected on socket Wr0hLcZONIM932aOAAAB with id 31761216
Chrome 96.0.4664.55 (Mac OS 10.15.7): Executed 3 of 3 SUCCESS (0.168 secs / 0.153 secs)
27 11 2021 12:49:33.132:ERROR [karma-server]: UncaughtException: SyntaxError: /Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/src/app/child-sample.ts: Argument name clash. (17:43)

  15 | var ChildSample = /** @class */ (function (_super) {
  16 |     __extends(ChildSample, _super);
> 17 |     function ChildSample(override, myArg1, override, myArg2) {
     |                                            ^
  18 |         var _this = _super.call(this, myArg1, myArg2) || this;
  19 |         _this.override = override;
  20 |         _this.override = override;
    at Parser._raise (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:541:17)
    at Parser.raiseWithData (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:534:17)
    at Parser.raise (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:495:17)
    at Parser.checkLVal (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:11075:20)
    at Parser.checkParams (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:12820:12)
    at Parser.<anonymous> (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:12795:14)
    at Parser.parseBlockOrModuleBlockBody (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:13964:23)
    at Parser.parseBlockBody (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:13932:10)
    at Parser.parseBlock (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:13916:10)
    at Parser.parseFunctionBody (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:12786:24)
27 11 2021 12:49:33.133:ERROR [karma-server]: SyntaxError: /Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/src/app/child-sample.ts: Argument name clash. (17:43)

  15 | var ChildSample = /** @class */ (function (_super) {
  16 |     __extends(ChildSample, _super);
> 17 |     function ChildSample(override, myArg1, override, myArg2) {
     |                                            ^
  18 |         var _this = _super.call(this, myArg1, myArg2) || this;
  19 |         _this.override = override;
  20 |         _this.override = override;
    at Parser._raise (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:541:17)
    at Parser.raiseWithData (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:534:17)
    at Parser.raise (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:495:17)
    at Parser.checkLVal (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:11075:20)
    at Parser.checkParams (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:12820:12)
    at Parser.<anonymous> (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:12795:14)
    at Parser.parseBlockOrModuleBlockBody (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:13964:23)
    at Parser.parseBlockBody (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:13932:10)
    at Parser.parseBlock (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:13916:10)
    at Parser.parseFunctionBody (/Users/spt/Work/Uxeed/sandbox/issues-sabarivka-ts-override/node_modules/@babel/parser/lib/index.js:12786:24) {
  loc: Position { line: 17, column: 43 },
  pos: 785,
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'ParamDupe'
}
TOTAL: 3 SUCCESS

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
Chrome 96.0.4664.55 (Mac OS 10.15.7) ERROR
  Disconnected Client disconnected from CONNECTED state (transport close)
Chrome 96.0.4664.55 (Mac OS 10.15.7): Executed 3 of 3 SUCCESS (0.168 secs / 0.153 secs)
Chrome 96.0.4664.55 (Mac OS 10.15.7) ERROR
  Disconnected Client disconnected from CONNECTED state (transport close)
npm ERR! Test failed.  See above for more details.
```

```ts
import { BaseSample } from './base-sample';

export class ChildSample extends BaseSample {
    constructor(
        public override myArg1: string,
        public override myArg2: string
    ) {
        super(myArg1, myArg2);
    }
}
```

### I can get tests to pass if:
- Remove sabarivka reporter from `karma.conf.js`
- Write a simple test spec for the classes that are using the `override` keyword

## My Environment

```
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "karma-sabarivka-reporter": "^3.2.5",
```

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.13
Node: 14.15.5
Package Manager: npm 6.14.11
OS: darwin x64

Angular: 12.2.13
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.13
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            12.2.13
@angular-devkit/schematics      12.2.13
@schematics/angular             12.2.13
rxjs                            6.6.7
typescript                      4.3.5
```

Please let me know if I can help in any way.

**Comment by kopach** [comment]
Hi @sebastianteres, thanks for using this lib and your contribution. I'll try to look at this soon

**Comment by kopach** [comment]
Hi @sebastianteres, I've just released new version (v3.3.1). Could you try it out, please? It seems to work for me on your test project.

**Comment by kopach** [comment]
Hi @sebastianteres, I'm closing this issue. Feel free to reopen it, if needed.

**Comment by sebastianteres** [comment]
@kopach I just confirmed this fix works great.
Thank you 👍 

I took my sweet time didn't I... apologies Sir!
